# Generated by Django 3.2.9 on 2021-11-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preference',
            field=models.IntegerField(default=28),
            preserve_default=False,
        ),
    ]
