# Generated by Django 3.2.9 on 2021-11-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.IntegerField(default=28),
        ),
    ]
