# Generated by Django 3.2.9 on 2021-11-23 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
